server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0&autosave=conservative
    username: postgres.snvasvzrqiordsgmfcai
    password: fusenfellow3
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://snvasvzrqiordsgmfcai.supabase.co/auth/v1

# Supabase Configuration
supabase:
  project-url: https://snvasvzrqiordsgmfcai.supabase.co
  jwt-secret: i686VSoGnUUwqzVeVDlulBLapDgMI8mH8jrrIs3EnTmoK11pcaSYwfwD5oAw6+W8+oDQMRuzNn5CliLUE0C/1w==
  anon-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNudmFzdnpycWlvcmRzZ21mY2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjk1OTMsImV4cCI6MjA2NTc0NTU5M30.Ya0nx3pHDl2Pwtatkjw_BjTvo_mxJmSlam2XKbEKTvA
  service-role-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNudmFzdnpycWlvcmRzZ21mY2FpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDE2OTU5MywiZXhwIjoyMDY1NzQ1NTkzfQ.YUlpVsDQJTsjEl3bV6X2O-32mGeIL42CMQOpODkqGMY

# Logging
logging:
  level:
    rebootedmvp: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    org.postgresql: DEBUG
    rebootedmvp.controller: INFO
    rebootedmvp.service: INFO
    rebootedmvp.security: INFO

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always