server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        generate_statistics: false
    open-in-view: false

# Supabase Configuration
supabase:
  project-url: ${SUPABASE_PROJECT_URL}
  jwt-secret: ${SUPABASE_JWT_SECRET}
  anon-key: ${SUPABASE_ANON_KEY}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}

# Logging - Reduced for production
logging:
  level:
    rebootedmvp: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.stat: WARN
    com.zaxxer.hikari: WARN
    org.springframework.jdbc: WARN
    org.postgresql: WARN
    rebootedmvp.controller: INFO
    rebootedmvp.service: INFO
    rebootedmvp.security: INFO

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always 